version: "3"

services:
  nexus:
    image: docker.io/sonatype/nexus3:${TAG:-latest}
    container_name: nexus
    hostname: nexus
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 8081:8081
    volumes:
      - "data:/nexus-data"

volumes:
  nexus-data:
    driver: local
