version: "2"

services:
  registry:
    image: registry:2
    restart: always
    container_name: registry
    ports:
      - 5000:5000
    volumes:
      - registry:/var/lib/registry

volumes:
  registry:
