version: "3"

services:
  scipy-notebook:
    image: docker.io/jupyter/scipy-notebook:${TAG:-python-3.10}
    container_name: scipy-notebook
    hostname: scipy-notebook
    user: root
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 8888:8888
    environment:
      - JUPYTER_TOKEN=easytoken
      - GRANT_SUDO=yes
    volumes:
      - work:/home/jovyan/work

volumes:
  work:
    driver: local
