version: "2.4"

services:
  kafka:
    image: confluentinc/cp-kafka:5.4.7
    depends_on:
      - zookeeper
    # restart: unless-stopped
    container_name: cp-kafka
    network_mode: host
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=localhost:32181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:29092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1

  zookeeper:
    image: confluentinc/cp-zookeeper:5.4.7
    # restart: unless-stopped
    container_name: cp-zookeeper
    network_mode: host
    environment:
      - ZOOKEEPER_CLIENT_PORT=32181
      - ZOOKEEPER_TICK_TIME=2000
      - ZOOKEEPER_SYNC_LIMIT=2
