version: "2"

services:
  redisgraph:
    image: docker.io/qdrant/qdrant:${TAG:-latest}
    hostname: qdrant
    network_mode: bridge
    ports:
      - 6333:6333
    environment:
      - TZ=Asia/Shanghai
      # - MALLOC_ARENA_MAX=2
