version: "3"

services:
  redisgraph:
    image: docker.io/qdrant/qdrant:${TAG:-latest}
    hostname: qdrant
    network_mode: bridge
    ports:
      - 6333:6333
    environment:
      - TZ=Asia/Shanghai
    deploy:
      resources:
        limits:
          cpus: "8.0"
          memory: "16g"
