version: "2"

services:
  mysql:
    image: bitnami/mysql:latest
    # restart: unless-stopped
    network_mode: bridge
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password123
    volumes:
      - ./volume/mysql-persistence:/bitnami/mysql/data
      - ./volume/my_custom.cnf:/opt/bitnami/mysql/conf/my_custom.cnf:ro
