version: "3.9"

services:
  qdrant_primary:
    image: docker.io/qdrant/qdrant:latest
    ports:
      - "6333:6333"
    environment:
      - QDRANT__CLUSTER__ENABLED=true
    command: ["./qdrant", "--uri", "http://qdrant_primary:6335"]

  qdrant_secondary:
    image: docker.io/qdrant/qdrant:latest
    environment:
      - QDRANT__CLUSTER__ENABLED=true
    command: ["./qdrant", "--bootstrap", "http://qdrant_primary:6335"]
