version: "2"

services:
  zookeeper:
    image: zookeeper
    hostname: zookeeper
    networks:
      - docker1

  bookie1:
    image: apache/bookkeeper
    depends_on:
      - zookeeper
    hostname: bookie1
    networks:
      - docker1
    environment:
      - JAVA_HOME=/usr/lib/jvm/java-11
      - BK_zkServers=zookeeper:2181
      - BK_zkLedgersRootPath=/ledgers

  bookie2:
    image: apache/bookkeeper
    depends_on:
      - zookeeper
    hostname: bookie2
    networks:
      - docker1
    environment:
      - JAVA_HOME=/usr/lib/jvm/java-11
      - BK_zkServers=zookeeper:2181
      - BK_zkLedgersRootPath=/ledgers

  bookie3:
    image: apache/bookkeeper
    depends_on:
      - zookeeper
    hostname: bookie3
    networks:
      - docker1
    environment:
      - JAVA_HOME=/usr/lib/jvm/java-11
      - BK_zkServers=zookeeper:2181
      - BK_zkLedgersRootPath=/ledgers

  dice:
    image: caiok/bookkeeper-tutorial
    depends_on:
      - zookeeper
      - bookie1
      - bookie2
      - bookie3
    networks:
      - docker1
    environment:
      - ZOOKEEPER_SERVERS=zookeeper:2181
      - BOOKKEEPER_SERVER=bookie3

networks:
  docker1:
    external: true
