version: "2"

services:
  zookeeper:
    image: docker.io/zookeeper:${TAG:-3.5}
    hostname: zookeeper

  bookie1:
    image: docker.io/apache/bookkeeper:latest
    depends_on:
      - zookeeper
    hostname: bookie1
    environment:
      - JAVA_HOME=/usr/lib/jvm/java-11
      - BK_zkServers=zookeeper:2181
      - BK_zkLedgersRootPath=/ledgers

  bookie2:
    image: docker.io/apache/bookkeeper:latest
    depends_on:
      - zookeeper
    hostname: bookie2
    environment:
      - JAVA_HOME=/usr/lib/jvm/java-11
      - BK_zkServers=zookeeper:2181
      - BK_zkLedgersRootPath=/ledgers

  bookie3:
    image: docker.io/apache/bookkeeper:latest
    depends_on:
      - zookeeper
    hostname: bookie3
    environment:
      - JAVA_HOME=/usr/lib/jvm/java-11
      - BK_zkServers=zookeeper:2181
      - BK_zkLedgersRootPath=/ledgers

  dice:
    image: docker.io/caiok/bookkeeper-tutorial:latest
    depends_on:
      - zookeeper
      - bookie1
      - bookie2
      - bookie3
    environment:
      - ZOOKEEPER_SERVERS=zookeeper:2181
