services:
  zookeeper:
    image: "bitnami/zookeeper:latest"
    container_name: single-zookeeper
    restart: unless-stopped
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_MAX_CLIENT_CNXNS=120
      - ZOO_AUTOPURGE_PURGEINTERVAL=24
      - >
        JVMFLAGS=-Xms1024m -Xmx1024m
        -XX:+UseG1GC
        -XX:MaxGCPauseMillis=50
        -XX:+AlwaysPreTouch
        -Djute.maxbuffer=4194304
        -Dzookeeper.admin.enableServer=false
        -Dzookeeper.serverCnxnFactory=org.apache.zookeeper.server.NettyServerCnxnFactory
    volumes:
      - data:/data
      - datalog:/datalog

volumes:
  data:
  datalog:
