services:
  zookeeper:
    image: zookeeper:3.5
    container_name: single-zookeeper
    restart: unless-stopped
    ports:
      - 2181:2181
    environment:
      - ZOO_MAX_CLIENT_CNXNS=120
      - ZOO_AUTOPURGE_PURGEINTERVAL=24
      - ZOO_ADMINSERVER_ENABLED=false
      - JVMFLAGS=-Xms1024m -Xmx1024m -XX:+UseG1GC -XX:MaxGCPauseMillis=50 -XX:+AlwaysPreTouch -Djute.maxbuffer=4194304 -Dzookeeper.serverCnxnFactory=org.apache.zookeeper.server.NettyServerCnxnFactory
    volumes:
      - data:/data
      - datalog:/datalog

volumes:
  data:
  datalog:
