---
version: "3"

services:
  weaviate:
    image: semitechnologies/weaviate:1.19.6
    network_mode: bridge
    ports:
      - 8080:8080
    volumes:
      - ./weaviate:/var/lib/weaviate
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      DEFAULT_VECTORIZER_MODULE: "none"
      ENABLE_MODULES: ""
      CLUSTER_HOSTNAME: "node1"
    command:
      - --host
      - 0.0.0.0
      - --port
      - "8080"
      - --scheme
      - http
