version: "3"

services:
  jemalloc:
    build:
      context: .
      x-bake:
        tags::
          - aaronchenwei/jemalloc:latest
          - aaronchenwei/jemalloc:5.3.0
        output: type=local,dest=./
