version: "2"

services:
  influxdb:
    image: influxdb:1.8
    restart: unless-stopped
    container_name: influxdb
    network_mode: host
    # ports:
    #   - 8086:8086
    volumes:
      - influxdb:/var/lib/influxdb

volumes:
  influxdb:
