services:
  zookeeper1:
    image: zookeeper:latest
    restart: always
    ports:
      - 2181:2181
    environment:
      - ZOO_MAX_CLIENT_CNXNS=120
      - ZOO_AUTOPURGE_PURGEINTERVAL=24
      - ZOO_ADMINSERVER_ENABLED=false
      - >
        JVMFLAGS=-Xms1024m -Xmx1024m
        -XX:+UseG1GC
        -XX:MaxGCPauseMillis=50
        -XX:+AlwaysPreTouch
        -Djute.maxbuffer=4194304
        -Dzookeeper.serverCnxnFactory=org.apache.zookeeper.server.NettyServerCnxnFactory
      - ZOO_MY_ID=1
      - ZOO_SERVERS=server.1=zookeeper1:2888:3888;2181 server.2=zookeeper2:2888:3888;2181 server.3=zookeeper3:2888:3888;2181

  zookeeper2:
    image: zookeeper
    restart: always
    ports:
      - 2182:2181
    environment:
      - ZOO_MAX_CLIENT_CNXNS=120
      - ZOO_AUTOPURGE_PURGEINTERVAL=24
      - ZOO_ADMINSERVER_ENABLED=false
      - >
        JVMFLAGS=-Xms1024m -Xmx1024m
        -XX:+UseG1GC
        -XX:MaxGCPauseMillis=50
        -XX:+AlwaysPreTouch
        -Djute.maxbuffer=4194304
        -Dzookeeper.serverCnxnFactory=org.apache.zookeeper.server.NettyServerCnxnFactory
      - ZOO_MY_ID=2
      - ZOO_SERVERS=server.1=zookeeper1:2888:3888;2181 server.2=zookeeper2:2888:3888;2181 server.3=zookeeper3:2888:3888;2181

  zookeeper3:
    image: zookeeper
    restart: always
    ports:
      - 2183:2181
    environment:
      - ZOO_MAX_CLIENT_CNXNS=120
      - ZOO_AUTOPURGE_PURGEINTERVAL=24
      - ZOO_ADMINSERVER_ENABLED=false
      - >
        JVMFLAGS=-Xms1024m -Xmx1024m
        -XX:+UseG1GC
        -XX:MaxGCPauseMillis=50
        -XX:+AlwaysPreTouch
        -Djute.maxbuffer=4194304
        -Dzookeeper.serverCnxnFactory=org.apache.zookeeper.server.NettyServerCnxnFactory
      - ZOO_MY_ID=3
      - ZOO_SERVERS=server.1=zookeeper1:2888:3888;2181 server.2=zookeeper2:2888:3888;2181 server.3=zookeeper3:2888:3888;2181
