version: "2.4"

networks:
  kafka-network:
    driver: bridge

services:
  kafka:
    image: "wurstmeister/kafka:2.12-2.4.1"
    depends_on:
      - zookeeper
    restart: unless-stopped
    networks:
      - kafka-network
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=INSIDE://:29092,OUTSIDE://localhost:9092
      - KAFKA_LISTENERS=INSIDE://:29092,OUTSIDE://:9092
      - KAFKA_INTER_BROKER_LISTENER_NAME=INSIDE
      # - KAFKA_JMX_OPTS=-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=kafka -Dcom.sun.management.jmxremote.rmi.port=1099
      # - JMX_PORT=1099

  zookeeper:
    image: "zookeeper:3.5"
    restart: unless-stopped
    networks:
      - kafka-network
    environment:
      - ZOO_MAX_CLIENT_CNXNS=120
      - ZOO_AUTOPURGE_PURGEINTERVAL=24
      - ZOO_ADMINSERVER_ENABLED=false
      - >
        JVMFLAGS=-Xms1024m -Xmx1024m
        -XX:+UseG1GC
        -XX:MaxGCPauseMillis=50
        -XX:+AlwaysPreTouch
        -Djute.maxbuffer=4194304
        -Dzookeeper.serverCnxnFactory=org.apache.zookeeper.server.NettyServerCnxnFactory
    ports:
      - "2181:2181"

  kafka-ui:
    image: provectuslabs/kafka-ui
    depends_on:
      - zookeeper
      - kafka
    restart: unless-stopped
    networks:
      - kafka-network
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
      # - KAFKA_CLUSTERS_0_READONLY=true
