version: "2"

services:
  almalinux:
    image: docker.io/almalinux:9
    container_name: almalinux-9
    network_mode: host
    tty: true
    stdin_open: true
    environment:
      - TZ=Asia/Shanghai
