version: "3"

services:
  almalinux-9:
    image: docker.io/almalinux:9
    container_name: almalinux-9
    network_mode: host
    tty: true
    stdin_open: true
    volumes:
      - shared:/root/shared
    environment:
      - TZ=Asia/Shanghai

volumes:
  shared:
    external: true
