version: "3"

services:
  spark:
    image: docker.io/bitnami/spark:3.3
    hostname: spark
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "8080:8080"
      - "4040:4040"
      - "4041:4041"
      - "7077:7077"
  spark-worker1:
    image: docker.io/bitnami/spark:3.3
    hostname: spark-worker1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
  spark-worker2:
    image: docker.io/bitnami/spark:3.3
    hostname: spark-worker2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
  spark-worker3:
    image: docker.io/bitnami/spark:3.3
    hostname: spark-worker3
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
  minio:
    image: docker.io/bitnami/minio:2022
    hostname: minio
    environment:
      - MINIO_ROOT_USER=minio-root-user
      - MINIO_ROOT_PASSWORD=minio-root-password
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - "minio_data:/data"
  pyspark-notebook:
    # bitnami/spark:3.3 is using python 3.8
    image: docker.io/jupyter/pyspark-notebook:python-3.8
    ports:
      - "8888:8888"
    environment:
      - TINI_SUBREAPER=true
    volumes:
      - "notebook_data:/home/jovyan/work"
volumes:
  minio_data:
    driver: local
  notebook_data:
    driver: local
