version: "2"

networks:
  kafka-network:
    driver: bridge

services:
  kafka:
    image: "wurstmeister/kafka:2.13-2.7.0"
    depends_on:
      - zookeeper
    restart: unless-stopped
    networks:
      - kafka-network
    ports:
      - "9094:9094"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=INSIDE://:9092,OUTSIDE://localhost:9094
      - KAFKA_LISTENERS=INSIDE://:9092,OUTSIDE://:9094
      - KAFKA_INTER_BROKER_LISTENER_NAME=INSIDE

  zookeeper:
    image: "zookeeper:3.5"
    restart: unless-stopped
    networks:
      - kafka-network
    ports:
      - "2181:2181"
