version: "3"

services:
  debian:
    build:
      context: .
      dockerfile: Dockerfile
    image: aaronchenwei/debian:bookworm
    container_name: debian-bookworm
    network_mode: host
    tty: true
    stdin_open: true
    volumes:
      - shared:/root/shared
    environment:
      - TZ=Asia/Shanghai

volumes:
  shared:
    external: true
