version: "2"

services:
  clickhouse:
    image: docker.io/clickhouse/clickhouse-server:${TAG:-latest}
    container_name: clickhouse
    hostname: clickhouse
    network_mode: bridge
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - data:/var/lib/clickhouse
      - log:/var/log/clickhouse-server/

volumes:
  data:
    driver: local
  log:
    driver: local
