version: "2"

services:
  clickhouse:
    image: clickhouse/clickhouse-server:${TAG:-latest}
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - data:/var/lib/clickhouse
      - log:/var/log/clickhouse-server/

volumes:
  data:
    driver: local
  log:
    driver: local
