version: "3"

services:
  jupyter-notebook:
    build:
      dockerfile: Dockerfile
    image: aaronchenwei/jupyter-notebook:latest
    container_name: jupyter-notebook
    hostname: jupyter-notebook
    user: root
    ports:
      - 8888:8888
    environment:
      - JUPYTER_TOKEN=easytoken
      - GRANT_SUDO=yes
    volumes:
      - work:/home/jovyan/work

volumes:
  work:
    driver: local
