version: "3"

services:
  scipy-notebook:
    build:
      dockerfile: Dockerfile
    image: aaronchenwei/scipy-notebook:latest
    container_name: scipy-notebook
    hostname: scipy-notebook
    user: root
    restart: unless-stopped
    ports:
      - 8888:8888
    environment:
      - JUPYTER_TOKEN=easytoken
      - GRANT_SUDO=yes
    volumes:
      - work:/home/jovyan/work

volumes:
  work:
    driver: local
