version: "2"

services:
  mysql:
    image: docker.io/mysql:${TAG:-8-debian}
    command:
      [
        "--default-authentication-plugin=mysql_native_password",
        "--innodb_buffer_pool_size=8G",
        "--innodb_log_file_size=512M",
        "--lower_case_table_names=1",
        "--max_connections=1001",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]
    # restart: always
    network_mode: bridge
    ports:
      - 3306:3306
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=example
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:
    driver: local
