version: "3"

services:
  activemq:
    build:
      context: .
      dockerfile: Dockerfile
    image: "aaronchenwei/activemq:5.18.0"
    container_name: "activemq"
    network_mode: bridge
    hostname: activemq
    ports:
      - 61616:61616
    volumes:
      - data:/data/activemq
      - log:/var/log/activemq

volumes:
  data:
    driver: local
  log:
    driver: local
