version: "3"

services:
  janusgraph:
    image: docker.io/janusgraph/janusgraph:latest
    container_name: janusgraph
    hostname: janusgraph
    network_mode: bridge
    ports:
      - "8182:8182"
    # The mounted volume only makes sense if JanusGraph is being run with the BerekeleyDB storage.
    volumes:
      - "janusgraph:/var/lib/janusgraph"

volumes:
  janusgraph:
    driver: local
