networks:
  kafka-net:
    driver: bridge

services:
  zookeeper:
    image: "bitnami/zookeeper:3.6"
    container_name: zookeeper
    networks:
      - kafka-net
    ports:
      - "2181:2181"
    environment:
      - ZOO_ENABLE_AUTH=yes
      - ZOO_SERVER_USERS=zookeeper
      - ZOO_SERVER_PASSWORDS=zkpass
      - ZOO_CLIENT_USER=zkclient
      - ZOO_CLIENT_PASSWORD=zkpass
    volumes:
      - ./zookeeper/data:/bitnami/zookeeper
  kafka:
    image: "bitnami/kafka:2"
    container_name: kafka
    networks:
      - kafka-net
    ports:
      - "9092:9092"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=no
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,CLIENT://:9093,
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:9092,CLIENT://localhost:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:SASL_PLAINTEXT,CLIENT:SASL_PLAINTEXT
      - KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL=PLAIN
      # Client credentials
      - KAFKA_CLIENT_USER=client1
      - KAFKA_CLIENT_PASSWORD=pass1
      # Interbroker credentials
      - KAFKA_INTER_BROKER_USER=interbrokeruser
      - KAFKA_INTER_BROKER_PASSWORD=interbrokerpass
      # Zookeeper credentials
      - KAFKA_ZOOKEEPER_PROTOCOL=SASL
      - KAFKA_ZOOKEEPER_USER=zookeeper
      - KAFKA_ZOOKEEPER_PASSWORD=zkpass
    volumes:
      - ./kafka/data:/bitnami/kafka
    depends_on:
      - zookeeper
