version: "2"

services:
  postgres:
    image: docker.io/postgres:14
    container_name: postgres
    network_mode: bridge
    ports:
      - "5432:5432"
    environment:
      - TZ=Asia/Shanghai
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=bootcamp
    volumes:
      - postgres:/var/lib/postgres
    command: postgres -c 'shared_buffers=4GB' -c 'max_connections=200'

volumes:
  postgres:
    driver: local
