version: "3"

services:
  nexus:
    image: docker.io/sonatype/nexus3:${TAG:-latest}
    container_name: nexus
    hostname: nexus
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 8081:8081
    volumes:
      - "data:/nexus-data"
    environment:
      - TZ=Asia/Shanghai
      - MALLOC_ARENA_MAX=1
      - MALLOC_MMAP_THRESHOLD_=131072
      - MALLOC_TRIM_THRESHOLD_=16384
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: "8g"

volumes:
  data:
    driver: local
