version: "3"

services:
  activemq:
    build:
      context: .
      dockerfile: Dockerfile
    image: "aaronchenwei/activemq:5.17.3"
    container_name: "activemq"
    ports:
      - 61616:61616
    volumes:
      - ./volumes/activemq/data:/data/activemq
      - ./volumes/activemq/log:/var/log/activemq
