version: "3"

services:
  influxdb:
    image: influxdb:2.7-alpine
    container_name: influxdb-v2
    hostname: influxdb-v2
    # network_mode: host
    network_mode: bridge
    ports:
      - 8086:8086
    volumes:
      - influxdb-v2:/var/lib/influxdb2

volumes:
  influxdb-v2:
    driver: local
