version: "3"

services:
  arangodb:
    image: docker.io/arangodb:latest
    ports:
      - 8529:8529
    environment:
      - ARANGO_ROOT_PASSWORD=example
    volumes:
      - arangodb_data_container:/var/lib/arangodb3
      - arangodb_apps_data_container:/var/lib/arangodb3-apps

volumes:
  arangodb_data_container:
  arangodb_apps_data_container:
