version: '2'

services:
  zookeeper:
    image: zookeeper:3.7
    network_mode: bridge
    # restart: unless-stopped
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    environment:
      - TZ=Asia/Shanghai
      - MALLOC_ARENA_MAX=2
      - ZOO_MY_ID=1
      - >
        JVMFLAGS=-Xms1024m -Xmx1024m
        -XX:+UseG1GC
        -XX:MaxGCPauseMillis=50
        -XX:+AlwaysPreTouch
        -Djute.maxbuffer=4194304
        -Dzookeeper.serverCnxnFactory=org.apache.zookeeper.server.NettyServerCnxnFactory
    volumes:
      - ${PWD}/zoo.cfg:/conf/zoo.cfg
      - ${PWD}/zoo.cfg.dynamic:/conf/zoo.cfg.dynamic
      - data:/data
      - datalog:/datalog
      - log:/logs

volumes:
  data:
  datalog:
  log:
