version: "2"

services:
  go-ethereum:
    image: ethereum/client-go:stable
    restart: unless-stopped
    network_mode: host
    # ports:
    #   - 8545:8545
    #   - 30303:30303
    command: "--http --http.addr 0.0.0.0"
