version: "3"

services:
  scipy-jupyter:
    image: jupyter/scipy-notebook:python-3.10
    hostname: scipy-notebook
    user: root
    restart: unless-stopped
    ports:
      - 8888:8888
    environment:
      - JUPYTER_TOKEN=easytoken
      - GRANT_SUDO=yes
    volumes:
      - ./volumes/work:/home/jovyan/work
