version: "3"

services:
  jupyter:
    image: docker.io/jupyter/scipy-notebook:${TAG:-latest}
    container_name: jupyter
    hostname: jupyter
    network_mode: bridge
    ports:
      - 8888:8888
    user: root
    environment:
      - JUPYTER_TOKEN=easytoken
      - GRANT_SUDO=yes
    volumes:
      - work:/home/jovyan/work

volumes:
  work:
    driver: local
