version: "2"

services:
  redis-server:
    image: redis:${TAG:-alpine}
    container_name: redis-server
    hostname: redis-server
    network_mode: bridge
    ports:
      - 6379:6379
    sysctls:
      net.core.somaxconn: "511"
  