version: "3"

services:
  redis-server:
    image: redis:${TAG:-bookworm}
    container_name: redis-server
    hostname: redis-server
    network_mode: bridge
    ports:
      - 6379:6379
    environment:
      - TZ=Asia/Shanghai
      - MALLOC_ARENA_MAX=1
    volumes:
      - data:/data

volumes:
  data:
    driver: local
