version: "2.4"

networks:
  kafka-network:
    driver: bridge

services:
  kafka:
    image: "wurstmeister/kafka:2.11-1.1.1"
    depends_on:
      - zookeeper
    restart: unless-stopped
    networks:
      - kafka-network
    ports:
      - "9094:9094"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=INSIDE://:9092,OUTSIDE://localhost:9094
      - KAFKA_LISTENERS=INSIDE://:9092,OUTSIDE://:9094
      - KAFKA_INTER_BROKER_LISTENER_NAME=INSIDE
      - KAFKA_JMX_OPTS=-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=kafka -Dcom.sun.management.jmxremote.rmi.port=1099
      - JMX_PORT=1099

  zookeeper:
    image: "zookeeper:3.5"
    restart: unless-stopped
    networks:
      - kafka-network
    ports:
      - "2181:2181"

  kafkamanager:
    image: kafkamanager/kafka-manager
    depends_on:
      - zookeeper
      - kafka
    restart: unless-stopped
    networks:
      - kafka-network
    ports:
      - "9000:9000"
    environment:
      - ZK_HOSTS=zookeeper:2181
