services:
  alpine:
    image: alpine:latest
    container_name: alpine
    # restart: always
    network_mode: host
    tty: true
    stdin_open: true
    ulimits:
      nofile:
        soft: 1024
        hard: 1024
