version: "2"

services:
  alpine:
    image: docker.io/alpine:latest
    container_name: alpine
    network_mode: host
    tty: true
    stdin_open: true
    ulimits:
      nofile:
        soft: 1024
        hard: 1024
