version: "2"

services:
  debian:
    image: docker.io/debian:bullseye
    container_name: debian-bullseye
    network_mode: host
    tty: true
    stdin_open: true
    environment:
      - TZ=Asia/Shanghai
