version: "2"

services:
  ubuntu:
    image: docker.io/ubuntu:jammy
    container_name: ubuntu-jammy
    network_mode: host
    tty: true
    stdin_open: true
    environment:
      - TZ=Asia/Shanghai
