version: "2"

services:
  ubuntu:
    build:
      context: .
      dockerfile: Dockerfile
    image: aaronchenwei/ubuntu-jammy
    container_name: ubuntu-jammy
    network_mode: host
    tty: true
    stdin_open: true
    volumes:
      - shared:/root/shared
    environment:
      - TZ=Asia/Shanghai

volumes:
  shared:
    external: true
