version: "2"

services:
  kali:
    image: docker.io/kalilinux/kali-rolling:latest
    container_name: kalilinux
    network_mode: host
    tty: true
    stdin_open: true
    volumes:
      - shared:/root/shared
    environment:
      - TZ=Asia/Shanghai

volumes:
  shared:
    external: true
