version: "2.4"

services:
  mysqld:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    network_mode: bridge
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - mysql:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    network_mode: bridge
    ports:
      - 8080:8080

volumes:
  mysql:
