version: "2"

services:
  ubuntu:
    image: docker.io/ubuntu:focal
    container_name: ubuntu-focal
    network_mode: host
    tty: true
    stdin_open: true
    environment:
      - TZ=Asia/Shanghai
