version: '3'

services:
  agency1:
    image: docker.io/arangodb:latest
    hostname: 'arangodb-agency1'
    container_name: 'arangodb-agency1'
    networks:
      - arango_net
    environment:
      - ARANGO_NO_AUTH=1
    expose:
      - '5001'
    volumes:
      - ./arangodb/agency1.conf:/etc/arangodb3/arangod.conf
      - ./arangodb/data/agency1:/var/lib/arangodb3/

  agency2:
    image: docker.io/arangodb:latest
    hostname: 'arangodb-agency2'
    container_name: 'arangodb-agency2'
    depends_on:
      - "agency1"
    networks:
      - arango_net
    environment:
      - ARANGO_NO_AUTH=1
    expose:
      - '5002'
    volumes:
      - ./arangodb/agency2.conf:/etc/arangodb3/arangod.conf
      - ./arangodb/data/agency2:/var/lib/arangodb3/

  agency3:
    image: docker.io/arangodb:latest
    hostname: 'arangodb-agency3'
    container_name: 'arangodb-agency3'
    depends_on:
      - "agency1"
    networks:
      - arango_net
    environment:
      - ARANGO_NO_AUTH=1
    expose:
      - '5003'
    volumes:
      - ./arangodb/agency3.conf:/etc/arangodb3/arangod.conf
      - ./arangodb/data/agency3:/var/lib/arangodb3/

  coordinator1:
    image: docker.io/arangodb:latest
    hostname: 'arangodb-coordinator1'
    container_name: 'arangodb-coordinator1'
    networks:
      - arango_net
    environment:
      - ARANGO_NO_AUTH=1
    ports:
      - '7001:7001'
    expose:
      - '7001'
    volumes:
      - ./arangodb/coord1.conf:/etc/arangodb3/arangod.conf
      - ./arangodb/data/coordinator1:/var/lib/arangodb3/

  coordinator2:
    image: docker.io/arangodb:latest
    hostname: 'arangodb-coordinator2'
    container_name: 'arangodb-coordinator2'
    networks:
      - arango_net
    environment:
      - ARANGO_NO_AUTH=1
    ports:
      - '7002:7002'
    expose:
      - '7002'
    volumes:
      - ./arangodb/coord2.conf:/etc/arangodb3/arangod.conf
      - ./arangodb/data/coordinator2:/var/lib/arangodb3/

  db1:
    image: docker.io/arangodb:latest
    hostname: 'arangodb-db1'
    container_name: 'arangodb-db1'
    networks:
      - arango_net
    environment:
      - ARANGO_NO_AUTH=1
    expose:
      - '6001'
    volumes:
      - ./arangodb/dbserver1.conf:/etc/arangodb3/arangod.conf
      - ./arangodb/data/db1:/var/lib/arangodb3

  db2:
    image: docker.io/arangodb:latest
    hostname: 'arangodb-db2'
    container_name: 'arangodb-db2'
    networks:
      - arango_net
    environment:
      - ARANGO_NO_AUTH=1
    expose:
      - '6002'
    volumes:
      - ./arangodb/dbserver2.conf:/etc/arangodb3/arangod.conf
      - ./arangodb/data/db2:/var/lib/arangodb3

  db3:
    image: docker.io/arangodb:latest
    hostname: 'arangodb-db3'
    container_name: 'arangodb-db3'
    networks:
      - arango_net
    environment:
      - ARANGO_NO_AUTH=1
    expose:
      - '6003'
    volumes:
      - ./arangodb/dbserver3.conf:/etc/arangodb3/arangod.conf
      - ./arangodb/data/db3:/var/lib/arangodb3

networks:
  arango_net:
    driver: bridge
