version: "3"

services:
  fedora-39:
    build:
      context: .
      dockerfile: Dockerfile
    image: aaronchenwei/fedora:39
    container_name: fedora-39
    network_mode: host
    tty: true
    stdin_open: true
    environment:
      - TZ=Asia/Shanghai
  
