version: "2.4"

services:
  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    # restart: unless-stopped
    network_mode: bridge
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password123
    volumes:
      - ./volume/conf.d:/etc/mysql/conf.d
      - ./volume/data:/var/lib/mysql
