version: "3"

services:
  qdrant:
    image: docker.io/qdrant/qdrant:${TAG:-latest}
    hostname: qdrant
    network_mode: bridge
    ports:
      - 6333:6333
      - 6334:6334
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./data/qdrant_storage:/qdrant/storage
      - ./custom_config.yaml:/qdrant/config/production.yaml
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "16.0"
    #       memory: "32g"
