version: "3"

services:
  qdrant:
    image: docker.io/qdrant/qdrant:${TAG:-latest}
    hostname: qdrant
    network_mode: bridge
    ports:
      - 6333:6333
    environment:
      - TZ=Asia/Shanghai
      - MALLOC_ARENA_MAX=2
    volumes:
      - ./data/qdrant_storage:/qdrant/storage
    deploy:
      resources:
        limits:
          cpus: "8.0"
          memory: "16g"
