version: "2"

services:
  zookeeper1:
    image: docker.io/bitnami/zookeeper:3.5
    ports:
      - "12181:2181"
      - "12888:2888"
      - "13888:3888"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVER_ID=1
      - ZOO_SERVERS=0.0.0.0:2888:3888,zookeeper2:2888:3888,zookeeper3:2888:3888
    networks:
      - zk_network

  zookeeper2:
    image: docker.io/bitnami/zookeeper:3.5
    ports:
      - "22181:2181"
      - "22888:2888"
      - "23888:3888"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVER_ID=2
      - ZOO_SERVERS=zookeeper1:2888:3888,0.0.0.0:2888:3888,zookeeper3:2888:3888
    networks:
      - zk_network

  zookeeper3:
    image: docker.io/bitnami/zookeeper:3.5
    ports:
      - "32181:2181"
      - "32888:2888"
      - "33888:3888"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVER_ID=3
      - ZOO_SERVERS=zookeeper1:2888:3888,zookeeper2:2888:3888,0.0.0.0:2888:3888
    networks:
      - zk_network

networks:
  zk_network:
    driver: bridge
